name: publish site
on:
  push:
    branches:
      - 2026
  pull_request:
    branches:
      - 2026
jobs: 
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force